### ISSUE TITLE
CreateDatabaseIfNotExists

### ISSUE THREAD

**Issue by speckosaurus** [kamranayub/pluralsight-ravendb-4-getting-started#3]
Hi, I'm working through the course but can't find the full code for the CreateDatabaseIfNotExists method. It isn't all shown on the screen and I haven't been able to find it anywhere else in the project. Can you help?

**Comment by kamranayub** [comment]
Since you closed this I assume you found it! But for posterity it's right here: https://github.com/kamranayub/pluralsight-ravendb-4-getting-started/blob/master/src/final/DocumentStoreHolder.cs#L53

It was a little beyond the scope of a "beginner" course but I wanted to include it because it's a Real Thing You Have to Do Sometimes ™️  👍 

This reminds me it'd be a short and sweet blog post to write, thanks for asking!
